import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        StringBuilder res = new StringBuilder();
        res.append("============= Order details =============\n");
        List<String> idCollect = inputs.stream().map(element->element.substring(0,element.indexOf("x")-1)).collect(Collectors.toList());
        int length = inputs.get(0).length();
        List<Integer> countCollect = inputs.stream().map(element->Integer.valueOf(element.substring(length-1,length))).collect(Collectors.toList());
        List<Item> itemList = itemRepository.findAll();
        List<SalesPromotion> salesPromotionList = salesPromotionRepository.findAll();
        List<String> salesItemList = salesPromotionList.get(1).getRelatedItems();
        List<String> salesItemName = new ArrayList<>();
        int totalPrice = 0,firstPromotionPrice=0,secondPromotionPrice=0;
        for(Item item:itemList){
            for(int i=0;i<inputs.size();i++){
                if(item.getId().equals(idCollect.get(i))){
                    if(salesItemList.contains(idCollect.get(i))){
                        secondPromotionPrice+=(item.getPrice()/2)*countCollect.get(i);
                        salesItemName.add(item.getName());
                    }else {
                        secondPromotionPrice+=item.getPrice()*countCollect.get(i);
                    }
                    totalPrice+=item.getPrice()*countCollect.get(i);
                    firstPromotionPrice+=item.getPrice()*countCollect.get(i);
                    res.append(item.getName()).append(" x ").append(countCollect.get(i)).append(" = ").append((int) (item.getPrice() * countCollect.get(i))).append(" yuan\n");
                    break;
                }
            }
        }
        res.append("-----------------------------------\n");
        if(firstPromotionPrice>=30){
            firstPromotionPrice-=6;
        }
        if(totalPrice<=firstPromotionPrice && totalPrice<=secondPromotionPrice){
            res.append("Total: ").append(totalPrice).append(" yuan\n");
            res.append("===================================");
        }else if(firstPromotionPrice<totalPrice && firstPromotionPrice<=secondPromotionPrice){
            res.append("Promotion used:\n");
            res.append("Deduct 6 yuan when the order reaches 30 yuan, saving 6 yuan\n"+"-----------------------------------\n");
            res.append("Total: ").append(firstPromotionPrice).append(" yuan\n");
            res.append("===================================");
        }else {
            res.append("Promotion used:\n");
            res.append("Half price for certain dishes (");
            String saleItem = salesItemName.stream().reduce("",(preElem,curElem)->preElem+","+curElem);
            res.append(saleItem.substring(1));
            res.append(")，saving ").append(totalPrice - secondPromotionPrice).append(" yuan\n");
            res.append("-----------------------------------\n");
            res.append("Total: ").append(secondPromotionPrice).append(" yuan\n");
            res.append("===================================");
        }
        return res.toString();
    }
}